#!/bin/bash

# DEBUG_ON=yes

# for debugging messages
DEBUG() {
 [[ $DEBUG_ON ]] && echo "$@\n" || :
}

# for checking errors - and exiting if any - call as
#  check_errs $? 'Some error message'
check_errs()
{
  # Function. Parameter 1 is the return code
  # Para. 2 is text to display on failure.
  if [ "${1}" -ne "0" ]; then
    echo "ERROR # ${1} : ${2}"
    exit ${1}
  fi
}

export -f DEBUG
export -f check_errs
